stages:
  - build
  - push

build:
  stage: build
  script:
    - docker build -t matchaitv/ci_android_fastlane:latest .

push_latest:
  stage: push
  only:
    - master
  script:
    - docker push matchaitv/ci_android_fastlane:latest
